In [17]:
import numpy as np #(can run min max sum median stdev etc.)

In [18]:
%%timeit
[x ** 2 for x in range(1, 1_000_000)]

358 ms ± 6.29 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [19]:
%%timeit # NP is much faster
np.arange(1, 1_000_000)**2

2.58 ms ± 45.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [21]:
# C is closer to the metal than python
# Assembly is closer to the metal than C
# Processor instruction sets are closer to the metal
370/3.04

121.71052631578947

In [24]:
# Lets make our first numpy array 

x = [1,2,3,4,5]
x = np.array(x) # this makes the numpy array 

x, type(x) # nd = n dimensional array (multiple arrays)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

In [25]:
# Tells us the shape of our n-dimensional array 
x.shape

(5,)

In [27]:
matrix = np.array ([
    [1,2,3],
    [4,5,6],
    [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
type(matrix)

numpy.ndarray

In [29]:
# List index syntax works on numpy arrays
matrix[0] # first row of the matrix

array([1, 2, 3])

In [42]:
matrix[0][0] 
#or
matrix[0,0] # gives first element of the array (first zero is the row and the secound zero is the elemtnt)

1

In [43]:
x, x[1:3] # gives subvectors of our vectors

(array([1, 2, 3, 4, 5]), array([2, 3]))

In [45]:
a = np.array(range(1,100))
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [48]:
# How to get min max stdev etc. Creates a tupil 
a.sum(), a.mean(), a.min(), a.max(), a.std()

(4950, 50.0, 1, 99, 28.577380332470412)

In [49]:
# How to get median (This function must be called stright from the numpy plibray with np.())
np.median(a)

50.0

In [51]:
# Can use bollena arrays to filter throught the original array printing out a new array
b = np.array([2,3,4,5]) 
should_include_elements = np.array([False, True, False, True])

b[should_include_elements]

array([3, 5])

In [54]:
# You can use the array to filter out rows of a matrix.
should_include_elements = np.array([False, True, True])
matrix[should_include_elements]

# Arrays of booleans == Beating heart of filtering/transformaing arrays

array([[4, 5, 6],
       [7, 8, 9]])

In [299]:
x = np.array([1,2,3,4,5])

In [56]:
x == 3 #gives back bolloean value

array([False, False,  True, False, False])

In [57]:
x < -9

array([False, False, False, False, False])

In [61]:
# how to check for evens
x % 2 == 0

array([False,  True, False,  True, False])

In [67]:
# Bolean masking 
only_threes = x == 3
x[only_threes]

array([3])

In [68]:
# We dont need the extra variable, however we can do the foloowing
# I read this code almost like sql in head
# sleect x where x is equal to 3 
x[x==3]

array([3])

In [69]:
# Select x where x is greater than 3 
x[x>3]

array([4, 5])

In [300]:
# Select x where x divided by two leaves no remainder
evens_from_x  = x [x % 2 == 0]
evens_from_x

array([2, 4])

In [298]:
# Remove_evens 
def remove_evens(x):
    return x[x % 2 == 0]
remove_evens(x)

array([], dtype=int64)

In [296]:
# if you have a list in the remove evens call you need to define x as np.array(x)
def remove_evens(x):
    x = np.array(x)
    return x[x % 2 ==0]
remove_evens([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

array([ 4, 10, 12, -2,  0,  0,  0, -6])

# Intro Vecotrization 
- Loop like behaviour on a array w/o the loop

In [99]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [100]:
x + 1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [102]:
# Lets make an array of random numbers
# Start is inclusive end is exclusive
x = np.random.randint(1, 21)
x

19

In [104]:
x = np.random.randint(1, 21, 10) # thrid argument is the Size or number of dice to be rolled
x

array([12, 19, 11,  9, 16,  3, 17,  4,  7, 15])

In [108]:
# make python fall on its face 
a =[1,2,3]

In [110]:
a+1

TypeError: can only concatenate list (not "int") to list

In [111]:
# In pyhton how would we add ont to every itrm on this list 
[n+1 for n in a] # Cave man way 


[2, 3, 4]

In [112]:
x/10

array([1.2, 1.9, 1.1, 0.9, 1.6, 0.3, 1.7, 0.4, 0.7, 1.5])

In [113]:
x * x

array([144, 361, 121,  81, 256,   9, 289,  16,  49, 225])

In [114]:
x * x - 2 + 3 * x #Multiply vecotors/matrix by scalers

array([178, 416, 152, 106, 302,  16, 338,  26,  68, 268])

In [116]:
x - 2*x # vector/matrix  subtraction 

array([-12, -19, -11,  -9, -16,  -3, -17,  -4,  -7, -15])

In [120]:
# More liner algerbra tools
np.dot(x, x)

1551

In [119]:
np.linalg.norm(x) 

39.382737335030434

In [ ]:
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [243]:
import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])



In [132]:
#1) How many negative numbers are there?
def count_negative(a):
    return a[a < 0]
len(count_negative(a))


4

In [125]:
#2) How many positive numbers are there?
def count_positive(a):
    return a[a > 0]
len(count_positive(a))

5

In [242]:
#3) How many even positive numbers are there?
a = a[a % 2 == 0]
a = a[a > 0]
len(a)

3

In [246]:
#4) If you were to add 3 to each data point, how many positive numbers would there be?
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

a1 = a + 3
a1 = a1[a1 > 0]
len(a1)

10

In [252]:
#5) If you squared each number, what would the new mean and standard deviation be?
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

ar = a ** 2
ar = ar.mean(), ar.std()
ar

(74.0, 144.0243035046516)

In [270]:
#6) A common statistical operation on a dataset is centering. 
# This means to adjust the data such that the mean of the data is 0. 
# This is done by subtracting the mean from each data point. 
# Center the data set. See this link for more on centering.
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
x = a-a.mean()
x 

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [274]:
#7) Calculate the z-score for each data point. Recall that the z-score is given by:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
m = a-a.mean()
s = a.std()
a = a-a.mean()/a.std()
a

array([ 3.6278958,  9.6278958, 11.6278958, 22.6278958, -2.3721042,
       -1.3721042, -0.3721042, -0.3721042, -0.3721042, -6.3721042,
        2.6278958, -7.3721042])

In [276]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
x = sum(a)
x

55

In [279]:
min_of_a = min(a)
min_of_a

1

In [280]:
max_of_a = max(a)
max_of_a

10

In [282]:
mean_of_a= a.mean()
mean_of_a

5.5

In [293]:
product_of_a = a.prod()
product_of_a

3628800

In [314]:
odds_in_a = a[a % 2 != 0]
odds_in_a

array([1, 3, 5, 7, 9])

In [308]:
evens_in_a = a [a % 2 == 0]
evens_in_a

SyntaxError: invalid syntax (<ipython-input-308-c35f303d0956>, line 1)

In [320]:
squares_of_a = np.square(a)
squares_of_a

# or
squares_of_a = a**2
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [322]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

b = b.max()
b


AttributeError: 'list' object has no attribute 'max'